### ISSUE TITLE
Removal of dependency `javax.json`? (May reduce coldstart times)

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java-core#79]
The JSON library contains 92 classes and currently the core agent only uses one class significantly and a few others just to store some information. Removing this will mean that less classes have to be looked at and compiled within the JVM, so coldstart times should be improved slightly. 

The testing framework will still use it naturally.

**Comment by XerTheSquirrel** [comment]
@pselle I think this would be best on the backlog, it is not really that high of a priority and involves some work. The gain in coldstart and execution times will probably not be that great compared to the previous switching of the logging framework. What do you think?

**Comment by pselle** [comment]
@XerTheSquirrel Sounds okay, it seemed accessible, but if it is larger than small, let's move to the backlog

**Comment by XerTheSquirrel** [comment]
@pselle Okay!

**Comment by XerTheSquirrel** [comment]
Will be fixed by #212.
