### ISSUE TITLE
Logging vs printing to console

### ISSUE THREAD

**Issue by pselle** [iopipe/iopipe-java-core#8]
Reading the code, it seems that we print output to the console at times -- shouldn't we be using logging so that we/users can customize the log level? Ex. using log4j, suggested because that's what the default serverless Lambda project uses, and seems to be a norm in Java?

**Comment by XerTheSquirrel** [comment]
Now log4j2 is used instead of printing to the console directly in commit e63cd5c121a42bfa5a0666f401ee3bf083c91a6b. Note that IOPIPE_DEBUG is removed now because it no longer makes sense to use (the debug portions of IOPIPE are now configured with log4j2).
